[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
dimensions = { columns = 150, lines = 50 }
decorations = "full"
startup_mode = "Windowed"
option_as_alt = "Both"

[scrolling]
history = 1000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"
